apiVersion: v2
appVersion: 1.2.0
description: Apache APISIX Ingress Controller for Kubernetes
icon: https://apache.org/logos/res/apisix/apisix.png
keywords:
- ingress
- apisix
- nginx
- crd
maintainers:
- name: Tareya
name: apisix-ingress-controller
type: application
version: 0.7.1
